# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  desc "Deploy a new version to Alpha"
  lane :alpha do
  GRADLE_APK_OUTPUT_PATH="./app/build/outputs/apk/release/app-release.apk"
  GRADLE_AAB_OUTPUT_PATH="./app/build/outputs/apk/release/app.aab"
   version_code = increment_version_code(
      gradle_file_path: "./app/build.gradle"
    )
    gradle(task: "clean assembleRelease")
    
    supply(
      track:"alpha",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}",
      json_key:"./secure/service-account-file.json"
    )

    git_commit(
      path:"./app/build.gradle",
      message:"Fastlane Android released #{version_code} [ci skip]"
    )
  end


  desc "Deploy a new version to Internal"
  lane :internal do
  GRADLE_APK_OUTPUT_PATH="./app/build/outputs/apk/release/app-release.apk"
  GRADLE_AAB_OUTPUT_PATH="./app/build/outputs/apk/release/app.aab"
   version_code = increment_version_code(
      gradle_file_path: "./app/build.gradle"
    )
    gradle(task: "clean assembleRelease")
    
    supply(
      track:"internal",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}",
      json_key:"./secure/service-account-file.json"
    )

    # git_commit(
    #   path:"../../*",
    #   message:"Fastlane internal Android released #{version_code} [ci skip]"
    # )


  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
