name: CI CD

on:
  push:
    branches:
      - master
jobs:
  weekday_job:
    runs-on: ubuntu-latest
    env:
      ANDROID_LS_ALIAS: ${{ secrets.ANDROID_LS_ALIAS }}
      ANDROID_LS_PASSWORD: ${{ secrets.ANDROID_LS_PASSWORD }}
      ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
    steps:
      - name: "Hello world when it's Monday"
        run: echo "Hello $ANDROID_LS_ALIAS $ANDROID_LS_PASSWORD $ANDROID_KEYSTORE_PATH!"

  build-android:
    # needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      # - name: Build Android Release
      #   run: |
      #     cd android && ./gradlew assembleRelease
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-release.apk
      #     path: android/app/build/outputs/apk/release

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Run release alpha
        run: |
          cd android
          rm -rf Gemfile.lock
          bundle update --all
          gem update bundler
          ls -la
          bundle exec fastlane alpha
