name: CI CD

on:
  push:
    branches:
      - master
jobs:
  weekday_job:
    runs-on: ubuntu-latest
    env:
      ANDROID_LS_ALIAS: ${{ secrets.ANDROID_LS_ALIAS }}
      ANDROID_LS_PASSWORD: ${{ secrets.ANDROID_LS_PASSWORD }}
      ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
    steps:
      - name: 'Hello world'
        run: |
          echo "Hello $ANDROID_LS_ALIAS $ANDROID_LS_PASSWORD $ANDROID_KEYSTORE_PATH!"
          echo $GITHUB_REPOSITORY
          echo "${{ github.token }}"

  build-android:
    # needs: install-and-test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.7
          java-package: jdk
          distribution: 'zulu'

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release

      - uses: r0adkll/upload-google-play@v1
        name: Upload to PlayStore
        with:
          serviceAccountJson: './android/secure/service-account-file.json'
          packageName: com.democdci
          releaseFile: './android/app/build/outputs/apk/release/app-release.apk'
          track: alpha
          whatsNewDirectory: ./android/distribution/
          # mappingFile: ./android/app/build/outputs/mapping/release/mapping.txt
      # - name: Setup ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 2.7.2
      #     bundler-cache: true
      # - name: Run release alpha
      #   run: |
      #     cd android
      #     rm -rf Gemfile.lock
      #     bundle update --all
      #     gem update bundler
      #     ls -la
      #     bundle exec fastlane alpha
