name: CI CD

on:
  push:
    branches:
      - master
jobs:
  build-android:
    # needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release
      - name: released android using fastlane
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
          with:
          ruby-version: '2.7.2'
        run: cd android && bundle exec fastlane alpha
