name: CI CD

on:
  push:
    branches:
      - master
jobs:
  build-android:
    # needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Access APOD_API_KEY
        env:
          APOD_API_KEY: ${{ secrets.APOD_API_KEY }}
        run: echo APOD_API_KEY=\"$APOD_API_KEY\" > ./local.properties

      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      # - name: Build Android Release
      #   run: |
      #     cd android && ./gradlew assembleRelease
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-release.apk
      #     path: android/app/build/outputs/apk/release

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Run release alpha
        run: |
          cd android
          rm -rf Gemfile.lock
          bundle update --all
          gem update bundler
          ls -la
          bundle exec fastlane alpha
